### ISSUE TITLE
Link in README not working

### ISSUE THREAD

**Issue by Willmish** [Avanade/TechCommunityCalendar#466]
@leeenglestone The link to the Calendar is pointing to http://www.techcommunitycalendar.com/ instead of https://techcommunitycalendar.com/ (or is not correctly being redirected)

**Comment by leeenglestone** [comment]
Seems to be working for me @Willmish?

**Comment by Willmish** [comment]
Ah, works for me now too! I tested it in the office yesterday with Chris and it didn't work.
