### ISSUE TITLE
[bug/doc] Error on the README.md file

### ISSUE THREAD

**Issue by GmausDev** [Avanade/TechCommunityCalendar#602]
**Describe the bug**

The readme file shield images dont show de stars, issues properly.

**To Reproduce**

1. Go to (https://github.com/Avanade/TechCommunityCalendar)
2. Look at the shields
![imagen](https://github.com/Avanade/TechCommunityCalendar/assets/50465630/0e462c59-6de5-4ce7-ac37-427c860f78b6)

4. Check issues and stars.
![imagen](https://github.com/Avanade/TechCommunityCalendar/assets/50465630/09a34f63-fbb1-4b36-949f-14bc89e43507)

7. See error

**Expected behavior**
Stars and issues numbers must match.

**Screenshots**
Added in the steps

**Web browser :**

- Web browser: Firefox
- Web browser Version:Dont apply

**Additional context**

**Comment by flushthemoney** [comment]
I would like to solve this issue, kindly assign it to me.

**Comment by GmausDev** [comment]
Hi @flushthemoney, sure!
If you need help or something just write here your doubts, also consider all commits must be signed-off.

Welcome !!🥳🥳

**Comment by flushthemoney** [comment]
Hey @GmausDev I've sent in a PR, I've also fixed the license badge along with the issues and stars. Please use the **hacktoberfest-accepted** tag while merging.

**Comment by GmausDev** [comment]
Yes, now its under review. And remember you can take another issue!

Thx for collaborate!🥳🥳

**Comment by flushthemoney** [comment]
Sure, I'll go through some of the other issues as well👍
